# El nombre de tu microservicio
spring.application.name=backend-core

# ==========================================
# CONFIGURACIÓN DE BASE DE DATOS (MONGODB)
# ==========================================
# Aquí enlazamos tu backend con el contenedor de Docker
spring.data.mongodb.uri=mongodb://localhost:27017/db_gestion_procesos

# ==========================================
# CONFIGURACIONES OPCIONALES (Pero muy útiles)
# ==========================================
# Puerto donde correrá este microservicio (por defecto es 8080, 
# pero si vas a tener varios servicios en Java o Go al mismo tiempo, 
# es bueno asignarles puertos distintos, ej: 8081, 8082)
server.port=8080

# Esto te mostrará en la consola las consultas internas que hace Spring Data
# (Muy útil para debugear cuando algo no guarda bien)
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG