# Nombre del microservicio
spring.application.name=backend-core

# ==========================================
# CONFIGURACIÓN DE BASE DE DATOS (MONGODB)
# ==========================================
# 1. Intenta usar la variable MONGO_URL de Railway.
# 2. Si no existe (en tu PC), usa el localhost y la base de datos 'db_gestion_procesos'.
spring.data.mongodb.uri=${URL_MONGO_NUBE:mongodb://localhost:27017/db_gestion_procesos}
# ==========================================
# CONFIGURACIÓN DE RED (PUERTO)
# ==========================================
# Railway asigna un puerto aleatorio mediante la variable PORT.
# En tu PC seguirá usando el 8080.
server.port=${PORT:8080}

# ==========================================
# LOGS Y DEBUG
# ==========================================
# Muestra las consultas a la base de datos en la consola
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG        




