# Nombre del microservicio
spring.application.name=backend-core

# ==========================================
# CONFIGURACIÓN DE BASE DE DATOS (MONGODB)
# ==========================================
# Si Railway tiene la variable 'URL_MONGO_NUBE', la usará. 
# De lo contrario, usará localhost.
#spring.data.mongodb.uri=${URL_MONGO_NUBE:mongodb://localhost:27017/db_gestion_procesos}
spring.mongodb.uri=${URL_MONGO_NUBE:mongodb://localhost:27017/db_gestion_procesos}
# ==========================================
# CONFIGURACIÓN DE RED (PUERTO)
# ==========================================
server.port=${PORT:8081}

# ==========================================
# LOGS DE DEPURACIÓN (MODO DETECTIVE)
# ==========================================
# 1. Ver qué está pasando con las consultas de Spring Data
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# 2. Ver la conexión real del DRIVER de Mongo (Aquí veremos si elige el host correcto)
logging.level.org.mongodb.driver.cluster=DEBUG
logging.level.org.mongodb.driver.connection=DEBUG

# 3. Ver por qué Spring elige o ignora ciertas configuraciones
logging.level.org.springframework.boot.autoconfigure.logging=DEBUG

# 4. Ver detalles de la red y el servidor Tomcat
logging.level.org.apache.tomcat=INFO
logging.level.org.springframework.web=DEBUG